DROP TABLE EffectiveCare;
CREATE EXTERNAL TABLE EffectiveCare (PROVIDERID VARCHAR(8), 
HOSPITALNAME VARCHAR(52),
ADDRESS VARCHAR(46),
CITY VARCHAR(22),
STATE VARCHAR(4),
ZIPCODE VARCHAR(7),
COUNTY VARCHAR(22),
PHONE VARCHAR(12),
CONDITION VARCHAR(37),
MEASUREID VARCHAR(18),
MEASURENAME VARCHAR(137),
SCORE VARCHAR(44),
SAMPLE VARCHAR(15),
FOOTNOTE VARCHAR(181),
MEASURESTARTDATE VARCHAR(12),
MEASUREENDDATE VARCHAR(12))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/EffectiveCare';

-- Load the table from hadoop repo
LOAD DATA INPATH '/user/w205/hospital_compare/stripeffective_care.csv'
OVERWRITE INTO TABLE effectivecare;

DROP TABLE Hospitals;
CREATE EXTERNAL TABLE Hospitals (PROVIDERID VARCHAR(8), 
HOSPITALNAME VARCHAR(52),
ADDRESS VARCHAR(46),
CITY VARCHAR(22),
STATE VARCHAR(4),
ZIPCODE VARCHAR(7),
COUNTY VARCHAR(22),
PHONE VARCHAR(12),
HOSPITALTYPE VARCHAR(38),
HOSPITALOWNER VARCHAR(45))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/hospitals';

-- Load the table from hadoop repo
LOAD DATA INPATH '/user/w205/hospital_compare/striphospitals.csv'
OVERWRITE INTO TABLE hospitals;

DROP TABLE Measures;
CREATE EXTERNAL TABLE Measures (MEASURENAME VARCHAR(89), 
MEASUREID VARCHAR(20),
MEASSTARTQTR VARCHAR(8),
MEASSTARTDATE VARCHAR(12),
MEASENDQTR VARCHAR(8),
MEASENDDATE VARCHAR(12))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/measures';

-- Load the table from hadoop repo
LOAD DATA INPATH '/user/w205/hospital_compare/stripmeasureDates.csv'
OVERWRITE INTO TABLE measures;


DROP TABLE ReadmissionsAndDeaths;
CREATE EXTERNAL TABLE ReadmissionsAndDeaths (PROVIDERID VARCHAR(8), 
HOSPITALNAME VARCHAR(52),
ADDRESS VARCHAR(46),
CITY VARCHAR(22),
STATE VARCHAR(4),
ZIPCODE VARCHAR(7),
COUNTY VARCHAR(22),
PHONE VARCHAR(12),
MEASURENAME VARCHAR(89),
MEASUREID VARCHAR(20),
SCORE VARCHAR(44),
LOWEST VARCHAR(15),
HIGHEST VARCHAR(181),
FOOTNOTE VARCHAR(12),
MEASURESTARTDATE VARCHAR(12),
MEASUREENDDATE VARCHAR(12))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/ReadsAndDeaths';

-- Load the table from hadoop repo
LOAD DATA INPATH '/user/w205/hospital_compare/stripreadmissionsUndDeath.csv'
OVERWRITE INTO TABLE ReadmissionsAndDeaths ;


DROP TABLE Surveys;
CREATE EXTERNAL TABLE Surveys (PROVIDERID VARCHAR(8), 
HOSPITALNAME VARCHAR(52),
ADDRESS VARCHAR(46),
CITY VARCHAR(22),
STATE VARCHAR(4),
ZIPCODE VARCHAR(12),
COUNTY VARCHAR(22),
COMMNURSEAPTS VARCHAR(15), 
COMMNURSEIPTS VARCHAR(15), 
COMMNURSEDIMSCORE VARCHAR(15), 
COMMDOCSAPTS VARCHAR(15), 
COMMDOCSIPTS VARCHAR(15), 
COMMDOCSDIMSCORE VARCHAR(15), 
RESPSTAFFAPTS VARCHAR(15), 
RESPSTAFFIPTS VARCHAR(15), 
RESPSTAFFDIMSCORE VARCHAR(15), 
PAINMGTAPTS VARCHAR(15), 
PAINMGTIPTS VARCHAR(15), 
PAINMGTDIMSCORE VARCHAR(15), 
COMMMEDSAPTS VARCHAR(15), 
COMMMEDSIPTS VARCHAR(15), 
COMMMEDSDIMSCORE VARCHAR(15), 
CLEANQUIETAPTS VARCHAR(15), 
CLEANQUIETIPTS VARCHAR(15), 
CLEANQUIETDIMSCORE VARCHAR(15), 
DISCHARGEINFOAPTS VARCHAR(15), 
DISCHARGEINFOIPTS VARCHAR(15), 
DISCHARGEINFODIMSCORE VARCHAR(15), 
OVERALLRATEAPTS VARCHAR(15), 
OVERALLRATEIPTS VARCHAR(15), 
OVERALLRATEDIMSCORE VARCHAR(15))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/Surveys';

-- Load the table from hadoop repo
LOAD DATA INPATH '/user/w205/hospital_compare/stripsurveys_responses.csv'
OVERWRITE INTO TABLE Surveys ;
