DROP TABLE EffectiveCare;
CREATE EXTERNAL TABLE EffectiveCare (PROVIDERID TEXT(8), 
HOSPITALNAME TEXT(52),
ADDRESS TEXT(46),
CITY TEXT(22),
STATE TEXT(4),
ZIPCODE TEXT(7),
COUNTY TEXT(22),
PHONE TEXT(12),
CONDITION TEXT(37),
MEASUREID TEXT(18),
MEASURENAME TEXT(137),
SCORE TEXT(44),
SAMPLE TEXT(15),
FOOTNOTE TEXT(181),
MEASURESTARTDATE TEXT(12),
MEASUREENDDATE TEXT(12))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/sripeffective_care.csv';


DROP TABLE Hospitals;
CREATE EXTERNAL TABLE Hospitals (PROVIDERID TEXT(8), 
HOSPITALNAME TEXT(52),
ADDRESS TEXT(46),
CITY TEXT(22),
STATE TEXT(4),
ZIPCODE TEXT(7),
COUNTY TEXT(22),
PHONE TEXT(12),
HOSPITALTYPE TEXT(38),
HOSPITALOWNER TEXT(45))
FIELDS TERMINATED BY','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/striphospitals.csv';

DROP TABLE Measures;
CREATE EXTERNAL TABLE Hospitals (MEASURENAME TEXT(89), 
MEASUREID TEXT(20),
MEASSTARTQTR TEXT(8),
MEASSTARTDATE TEXT(12),
MEASENDQTR TEXT(8),
MEASENDDATE TEXT(12))
FIELDS TERMINATED BY','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/sripmeasures.csv';


DROP TABLE ReadmissionsAndDeaths;
CREATE EXTERNAL TABLE ReadsmissionsAndDeaths (PROVIDERID TEXT(8), 
HOSPITALNAME TEXT(52),
ADDRESS TEXT(46),
CITY TEXT(22),
STATE TEXT(4),
ZIPCODE TEXT(7),
COUNTY TEXT(22),
PHONE TEXT(12),
MEASURENAME TEXT(89),
MEASUREID TEXT(20),
SCORE TEXT(44),
LOWEST TEXT(15),
HIGHEST TEXT(181),
FOOTNOTE TEXT(12),
MEASURESTARTDATE TEXT(12)
MEASUREENDDATE TEXT(12))
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY','
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/sripReadsAndDeaths.csv';
